export const OBERVER_POPUP_MENU_TOGGLE = 'OBERVER_POPUP_MENU_TOGGLE';
export const OBSERVER_CLIENT_PREVENT_TOUCH = 'OBSERVER_CLIENT_PREVENT_TOUCH';

export const OBSERVER_INSIGHT_ADVICE_NOTICE = 'OBSERVER_INSIGHT_ADVICE_NOTICE';
