export const commonTableConfig = {
  border: true,
  index: true,
  indexLabel: '序号',
  align: 'center',
  menuAlign: 'center',
  menuWidth: '150',
  formWidth: '60%',
  selection: false,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  menuBtn: false,
  refreshBtn: true,
  columnBtn: true,
  menu: true,
  viewBtn: false,
  labelWidth: '150',
}
